server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_records_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/medical-realm

keycloak:
  auth-server-url: http://localhost:8080
  realm: medical-realm
  resource: medical-backend
  public-client: true

  # Admin credentials for the Keycloak Admin REST API
  admin:
    username: medicalrealadmin
    password: STRONGPASSWORD!@#


